# LLM API配置
# 向量存储配置
# 
vectorstore:
  metadata_path: "data/meta/retrieval_traits"
  persist_directory: "data/vectorstore"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"    # Alibaba-NLP/gte-Qwen2-7B-instruct   2025年02月09日 01:08:47 替换  sentence-transformers/all-MiniLM-L6-v2

# 角色确定配置
role_matching:
  top_k: 5  # 返回的最相关角色数量
  similarity_threshold: 0.7  # 相似度阈值
  main_character_threshold: 0.2  # 判断主角的阈值

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

# RAG配置
rag:
  max_context_length: 2048  # 上下文最大长度
  temperature: 0.7  # 生成温度
  top_p: 0.95  # 采样阈值 

# 通用配置
general:
  HF_ENDPOINT: True # 镜像 huggingface.co 域名。